---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: sweetrpg-PACKAGE-COMPONENT
  labels:
    release: prometheus

spec:
  podMetricsEndpoints:
    - port: http
  selector:
    matchLabels:
        platform: sweetrpg
        app: COMPONENT
        package: PACKAGE
        component: COMPONENT
  namespaceSelector:
    matchNames:
      - sweetrpg-admin
