# -*- coding: utf-8 -*-
__author__ = "Paul Schifferer <dm@sweetrpg.com>"
"""constants.py
Constants for keys and environment variable names
"""

AUTH0_CLIENT_ID = "AUTH0_CLIENT_ID"
AUTH0_CLIENT_SECRET = "AUTH0_CLIENT_SECRET"
AUTH0_CALLBACK_URL = "AUTH0_CALLBACK_URL"
AUTH0_DOMAIN = "AUTH0_DOMAIN"
AUTH0_AUDIENCE = "AUTH0_AUDIENCE"
AUTH0_LOGIN_URL = "AUTH0_LOGIN_URL"

KANKA_CLIENT_ID = "KANKA_CLIENT_ID"
KANKA_CLIENT_SECRET = "KANKA_CLIENT_SECRET"
KANKA_CALLBACK_URL = "KANKA_CALLBACK_URL"
KANKA_DOMAIN = "KANKA_DOMAIN"
KANKA_AUDIENCE = "KANKA_AUDIENCE"

SENTRY_DSN = "SENTRY_DSN"
SENTRY_ENV = "SENTRY_ENV"

APPLICATION_NAME = "sweetrpg-COMPONENT-web"
PROFILE_KEY = "profile"
JWT_PAYLOAD = "jwt_payload"
CURRENT_USER_ID = "current_user_id"

SEGMENT_WRITE_KEY = "SEGMENT_WRITE_KEY"

# Configuration
DEBUG = "DEBUG"
PORT = "PORT"
LOG_LEVEL = "LOG_LEVEL"
DB_HOST = "DB_HOST"
DB_PORT = "DB_PORT"
DB_USER = "DB_USER"
DB_PW = "DB_PW"
DB_NAME = "DB_NAME"
DB_OPTS = "DB_OPTS"
REDIS_HOST = "REDIS_HOST"
REDIS_PORT = "REDIS_PORT"
LOGSTASH_HOST = "LOGSTASH_HOST"
LOGSTASH_DB_PATH = "LOGSTASH_DB_PATH"
LOGSTASH_TRANSPORT = "LOGSTASH_TRANSPORT"
LOGSTASH_PORT = "LOGSTASH_PORT"
