---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - configmaps.yaml
  - deployment.yaml
  - service.yaml
secretGenerator:
  - name: sweetrpg-COMPONENT-web
    type: Opaque
    envs:
      - secrets.env
