name: Prepare Release

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  prepare:
    uses: sweetrpg/github-actions/.github/workflows/python-prepare-release.yaml@master
    with:
      version-file: src/sweetrpg_COMPONENT_web/__init__.py
    secrets: inherit
