name: PR

on:
    pull_request:
        branches: [develop, master]
        paths:
            - "src/**"
            - "tests/**"
            - pyproject.toml
            - uv.lock
            - "docs/**"
            - ".github/workflows/**"

permissions:
    contents: read

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          python: "3.14",
                          os: ubuntu-latest,
                      }
        steps:
            - uses: actions/checkout@v6
            - uses: astral-sh/setup-uv@v7
              with:
                  python-version: ${{ matrix.python }}
                  enable-cache: true
                  cache-dependency-glob: "uv.lock"
            - name: sync-deps
              run: uv sync --group test --frozen
            - name: tests
              run: uv run pytest -v tests
