name: PR

on:
    pull_request:
        branches: [develop]
        paths:
            - "src/**"
            - "tests/**"
            - setup.cfg
            - setup.py
            - tox.ini
            - "requirements/**"
            - "docs/**"

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          python: "3.11",
                          os: ubuntu-latest,
                          tox: py311,
                      }
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.python }}
            - name: update-pip
              run: |
                  pip install -U wheel
                  pip install -U setuptools
                  python -m pip install -U pip
            - name: get-pip-cache-dir
              id: pip-cache
              run: echo "::set-output name=dir::$(pip cache dir)"
            - name: cache-pip
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pip-cache.outputs.dir }}
                  key: pip|${{ runner.os }}|${{ matrix.python }}|${{ hashFiles('setup.py') }}|${{ hashFiles('requirements/*.txt') }}
            - name: install-utils
              run: pip install tox
            # - name: lint
            #   run: black --check -t py39 --diff --color src
            - name: tests
              run: tox -e ${{ matrix.tox }}
